language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

# notifications:
#   slack: electivegroup:ROEhNa2GlwAIIFD1vd7ds64V

matrix:
    fast_finish: true
    include:
          # Test the latest stable release
        - php: 7.1
        - php: 7.2
        - php: 7.3

install:
    - composer install --dev

script:
    - ./vendor/bin/phpunit 
